<div class="well-large">
    <h1>Licitaciones</h1>
</div>
<?php if (count($this->messages)) : ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul id="messages">
            <?php foreach ($this->messages as $message) : ?>
                <li><?php echo $this->escape($message); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<table class="table">
    <tr>
        <th>Tipo</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Estado</th>
        <th>Motivo del llamado</th>
        <th>Certificado</th>
    </tr>
    <?php foreach ($this->licitaciones as $licitacion) : ?>
        <tr>
            <td><?php echo $licitacion->getTipoDeContratacion()?></td>
            <td><?php echo $licitacion->getFechaDeApertura()?></td>
            <td><?php echo $licitacion->getHoraDeApertura().' hs.' ?></td>
            <td><?php echo ($licitacion->getActiva() == true) ? 'VIGENTE' : 'CADUCA' ?></td>
            <td><?php echo $licitacion->getDescripcion() ?></td>
            <td><a id="verPdf" name="<?php echo $licitacion->getId()?>" onclick="crearPdf('<?php echo $licitacion->getId()?>')" class="btn btn-success"><i class="icon-download"></i></a></td>
        </tr>
<?php endforeach; ?>
</table>