<br /><br />
<div class="well-large">
    <h1>Imagenes de la Galería Vendimial</h1>
</div>
<?php if ($this->imagenes): ?>
<div id="myCarousel" class="carousel slide"> <!--IMAGENES-->
    <div class="carousel-inner">
        <?php foreach ($this->imagenes as $index => $imagen) : ?>
        <?php if ($index == 0): ?>
        <div class="item active">
            <img src="<?php echo $this->url(array('module'=>'default','controller'=>'recursosv','action'=>$imagen->getUrl()))?>" alt="" class="imagenes-carousel">
            <div class="carousel-caption imagenes-texto">
                <p><?php echo $imagen->getDescripcion()?></p>
            </div>
        </div>
        <?php else : ?>
        <div class="item">
            <img src="<?php echo $this->url(array('module'=>'default','controller'=>'recursosv','action'=> $imagen->getUrl()))?>" alt="" class="imagenes-carousel">
            <div class="carousel-caption imagenes-texto">
                <p><?php echo $imagen->getDescripcion()?></p>
            </div>
        </div>
        <?php endif; endforeach; ?>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel --><!--FIN IMAGENES-->
<?php else: ?>
<h1>Aún No Hay Imágenes En la Galería</h1>
<?php endif; ?>

<a class="btn btn-success" href="<?php echo $this->url(array('module'=>'administracion','controller'=>'imagenes','action'=>'agregarimagen','vendimia'=>true),null,true)?>">Agregar Imágen a la galería vendimial</a>
<?php if ($this->imagenes) : ?>
<a class="btn btn-success" href="<?php echo $this->url(array('module'=>'administracion','controller'=>'imagenes','action'=>'administrar-galeria-vendimia'),null,true)?>">Administrar galería Vendimia</a>
        <?php endif; ?>
