<?php
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
if ($this->subseccion->getImagenes()->count() > 0) {
    $this->headMeta()->setName('og:title', $this->subseccion->getNombre())
            ->setName('og:image', $this->url(array('action' => $this->subseccion->getImagenes()->first()->getUrl()), 'recurso-seccion', true))
            ->setName('og:description', $this->subseccion->getContenido())
            ->setName('og:url', $this->url());
} else {
    $this->headMeta()->setName('og:title', $this->subseccion->getNombre())
            ->setName('og:description', $this->subseccion->getContenido())
            ->setName('og:url', $this->url());
}
?>
<img class="tab" src="<?php echo $this->baseUrl() . '/img/tab_2.png' ?>"/><!-- DIVISOR -->
<br />
<div class="seccion">
    <h2><?php echo $this->subseccion->getNombre() ?></h2>
    <ul class="nav nav-tabs hcd">
        <li class="active"><a href="#hcd" data-toggle="tab">H C D</a></li>
        <li><a href="#pdec" data-toggle="tab">Proyectos de declaraciones</a></li>
        <li><a href="#pord" data-toggle="tab">Proyectos de ordenanzas</a></li>
        <li><a href="#pres" data-toggle="tab">Proyectos de resoluciones</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="hcd">
            <?php if ($this->subseccion->getImagenes()->count() > 0) : ?>
                <?php if ($this->subseccion->getImagenes()->count() < 2) : ?>
                    <img src="<?php echo $this->url(array('action' => $this->subseccion->getImagenes()->first()->getUrl()), 'recurso-seccion', true) ?>" style="float: left;">
                <?php else: ?>
                    <div id="myCarousel" class="carousel slide"> <!--IMAGENES-->
                        <div class="carousel-inner">
                            <?php foreach ($this->subseccion->getImagenes() as $index => $imagen) : ?>
                                <?php if ($index == 0): ?>
                                    <div class="item active">
                                        <img src="<?php echo $this->url(array('action' => $imagen->getUrl()), 'recurso-seccion', true) ?>" alt="" class="imagenes-carousel">
                                    </div>
                                <?php else : ?>
                                    <div class="item">
                                        <img src="<?php echo $this->url(array('action' => $imagen->getUrl()), 'recurso-seccion', true) ?>" alt="" class="imagenes-carousel">
                                    </div>
                                <?php
                                endif;
                            endforeach;
                            ?>
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
                    </div><!-- /.carousel --><!--FIN IMAGENES-->   
                <?php
                endif;
            endif;
            ?>
            <a class="pull-right" href="#" 
               onclick="
                       window.open(
                               'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(location.href),
                               'facebook-share-dialog',
                               'width=626,height=436');
                       return false;">
                <img src="<?php echo $this->baseUrl() . '/img/compartir_en_face.png' ?>">
            </a>

            <br>
<?php echo $this->subseccion->getContenido() ?>

        </div>
        <div class="tab-pane" id="pdec">
            <br>
<?php foreach ($this->proyectosDec as $proyecto) :?>
                <div class="media">
                    <a class="pull-left" href="<?php echo $this->baseUrl() . '/proyectos/'.$proyecto->getDocumento() ?>" target="_blank" onClick="window.open(this.href, this.target, 'width=700,height=600');
return false;" role="button" data-toggle="modal" >
                        <img class="media-object" src="<?php echo $this->baseUrl() . '/img/pdf_file.png'?>">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading"><?php echo $proyecto->getTitulo()?></h4>
                        <p><?php echo $proyecto->getResumen()?></p>
                    </div> 
                </div>
<?php endforeach; ?>
        </div>
        <div class="tab-pane" id="pord">
                    <br>
<?php foreach ($this->proyectosOrd as $proyecto) :?>
                <div class="media">
                    <a class="pull-left" href="<?php echo $this->baseUrl() . '/proyectos/'.$proyecto->getDocumento() ?>" target="_blank" onClick="window.open(this.href, this.target, 'width=700,height=600');
return false;" role="button" data-toggle="modal">
                        <img class="media-object" src="<?php echo $this->baseUrl() . '/img/pdf_file.png'?>">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading"><?php echo $proyecto->getTitulo()?></h4>
                        <p><?php echo $proyecto->getResumen()?></p>
                    </div> 
                </div>
<?php endforeach; ?>
        </div>
        <div class="tab-pane" id="pres">
                    <br>
<?php foreach ($this->proyectosRes as $proyecto) :?>
                <div class="media">
                    <a class="pull-left" href="<?php echo $this->baseUrl() . '/proyectos/'.$proyecto->getDocumento() ?>" target="_blank" onClick="window.open(this.href, this.target, 'width=700,height=600');
return false;" role="button" data-toggle="modal" >
                        <img class="media-object" src="<?php echo $this->baseUrl() . '/img/pdf_file.png'?>">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading"><?php echo $proyecto->getTitulo()?></h4>
                        <p><?php echo $proyecto->getResumen()?></p>
                    </div> 
                </div>
<?php endforeach; ?>
        </div>
    </div>
</div>   
<script>
    activarLinkMenu('<?php echo $this->subseccion->getPadres()->first()->getNombre() ?>');
</script>