<img class="tab" src="<?php echo $this->baseUrl() . '/img/tab.png' ?>"/><!-- DIVISOR -->    
<h2>Novedades</h2>
    <div class='row-fluid'><!--NOTICIAS FILA 1-->
<?php foreach ($this->noticiasPrincipales as $index => $noticiap): ?>
                        <?php if ($index == 0 || $index == 3) : ?>
                <div class="row-fluid">    
                    <div class="span4 noticiasPrincipales">
                        <a href="<?php echo $this->url(array('id' => $noticiap->getId()),'noticia', true) ?>">
                            <?php if ($noticiap->getArchivoPrincipal()) : ?>
                                <img height="300" width="300" src="<?php
                                     echo $this->url(array('action' => $noticiap->getArchivoPrincipal()->getUrl()),'recurso-noticia',true)
                                     ?>">
        <?php endif; ?>
                            <h5><?php echo $noticiap->getTitulo() ?></h5>
                            <p><?php echo $noticiap->getCopete() ?></p>

                        </a>
                    </div>
                        <?php elseif ($index == 2 || $index == 5) : ?>   
                    <div class="span4 noticiasPrincipales">
                        <a href="<?php echo $this->url(array('id' => $noticiap->getId()), 'noticia', true) ?>">
                            <?php if ($noticiap->getArchivoPrincipal()) : ?>
                                <img height="300" width="300" src="<?php
                                     echo $this->url(array('action' => $noticiap->getArchivoPrincipal()->getUrl()),'recurso-noticia',true)
                                     ?>">
        <?php endif; ?>
                            <h5><?php echo $noticiap->getTitulo() ?></h5>
                            <p><?php echo $noticiap->getCopete() ?></p>

                        </a>
                    </div>
                </div>
                    <?php else: ?>
                <div class="span4 noticiasPrincipales">
                    <a href="<?php echo $this->url(array('id' => $noticiap->getId()), 'noticia', true) ?>">

                        <?php if ($noticiap->getArchivoPrincipal()) : ?>
                            <img height="300" width="300" src="<?php
                                 echo $this->url(array('action' => $noticiap->getArchivoPrincipal()->getUrl()),'recurso-noticia',true)
                                 ?>">
        <?php endif; ?>
                        <h5><?php echo $noticiap->getTitulo() ?></h5>
                        <p><?php echo $noticiap->getCopete() ?></p>

                    </a>
                </div>
    <?php endif; ?>
<?php endforeach; ?>