<?php
$this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
$this->headMeta()->setName('og:title', 'Vendimia Lavalle 2014. Romántica Cosecha de Amor')
        ->setName('og:image', 'http://www.lavallemendoza.gov.ar/img/afiche800x350.jpg')
        ->setName('og:description', 'Conocé todas las actividades de la vendimia departamental de Lavalle')
        ->setName('og:url', 'http://www.lavallemendoza.gov.ar/vendimia');
?>
<div class="vendimia container-fluid">
    <a class="pull-right" href="#" 
       onclick="
               window.open(
                       'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(location.href),
                       'facebook-share-dialog',
                       'width=626,height=436');
               return false;">
        <img src="<?php echo $this->baseUrl() . '/img/compartir_en_face.png' ?>">
    </a>
    <div class="row-fluid"><div class="span12"><center><h1>Cintia Denis Man, Reina Departamental</h1></center></div></div>
    <div class="row-fluid">
        <!-- CARROUSEL -->
        <div class="span4">
            <div id="myCarousel" class="carousel slide" width> <!--IMAGENES-->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="<?php echo $this->baseUrl() . '/img/reina2013/1.jpg' ?>">
                    </div>
                    <div class="item ">
                        <img src="<?php echo $this->baseUrl() . '/img/reina2013/2.jpg' ?>">
                    </div>
                    <div class="item ">
                        <img src="<?php echo $this->baseUrl() . '/img/reina2013/3.jpg' ?>">
                    </div>
                    <div class="item ">
                        <img src="<?php echo $this->baseUrl() . '/img/reina2013/4.jpg' ?>">
                    </div>
                    <div class="item ">
                        <img src="<?php echo $this->baseUrl() . '/img/reina2013/5.jpg' ?>">
                    </div>
                    <a class="left carousel-control" href="#myCarousel" data-slide="next">&lsaquo;</a>

                </div>
            </div>
        </div><!-- FIN CARROUSEL -->
        <div class="span4">

            <br>
            <h4>22 Años de Edad</h4>
            <h4>Estudia Comunicación Social</h4>
            <h4>Ojos color pardo</h4>
            <h4>Su Hobby es Cantar</h4>
            <h4>Fué elegida el 9 de febrero del 2013 en la "Vendimia del Vino de Tántas Lunas"</h4>
        </div>
        <div class="span4">
            <img style="float:right" src="<?php echo $this->baseUrl() . '/img/reina2013/atributos_chica_1.jpg' ?>">
        </div>
    </div>

    <?php if ($this->candidatas) : ?>
        <div class="efectoVendimia"><a href="#Candidatas" role="button" data-toggle="modal">Haz Click aquí para ver las candidatas a Reina Departamental 2014!</a></div>
        <hr>
        <h1>Imágenes</h1>
    <?php endif; ?>
    <?php if ($this->imagenes) : ?>
        <div id="links">
            <?php foreach ($this->imagenes as $imagen) : ?>
                <a href="<?php echo $this->url(array('action' =>$imagen->getUrl()), 'recurso-vendimia', true) ?>" title="<?php echo $imagen->getDescripcion() ?>">
                    <img src="<?php echo $this->url(array('action' => $imagen->getUrl()), 'recurso-vendimia-thumbnail', true) ?>">
                </a>
            <?php endforeach; ?>
        </div>
        <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
        <div id="blueimp-gallery" class="blueimp-gallery">
            <div class="slides"></div>
            <h3 class="title"></h3>
            <a class="prev">‹</a>
            <a class="next">›</a>
            <a class="close">×</a>
            <a class="play-pause"></a>
            <ol class="indicator"></ol>
        </div>        

    <?php endif; ?>


    <!-- AGENDA VENDIMIAL -->
    <div class="row-fluid">
        <div class="span12">
            <center><h1>Agenda Vendimial</h1></center>
            <table class="table">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Evento</th>
                        <th>Lugar</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Martes 14/01</td>
                        <td colspan="2">
                            <table class="table">
                                <tr>
                                    <td>Curso de Oratoria (Dirigido por Belén Quiroga-Mario Quiroga) 
                                        <p>Horario: 8:30 a 11:00</p></td>
                                    <td rowspan="2">Casa de la Cultura en Villa Tulumaya</td>
                                </tr>
                                <tr>
                                    <td>Instrucción en Danzas Folclóricas(Dirigido por los profesores Diego Fiore y Carina Diaz) 
                                        <p>horario: 11:00 a 14:00</p></td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                    <tr>
                        <td>Miercoles 15/01</td>
                        <td colspan="2">
                            <table class="table">
                                <tr>
                                    <td>Curso de Oratoria (Dirigido por Belén Quiroga-Mario Quiroga)
                                        <p>horario: 8:30 a 11:00</p></td>
                                    <td rowspan="2">Casa de la Cultura en Villa Tulumaya</td>
                                </tr>
                                <tr>
                                    <td>Instrucción en Danzas Folclóricas(Dirigido por los profesores Diego Fiore y Carina Diaz)
                                        <p>Horario: 11:00 a 14:00</p></td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                    <tr>
                        <td>Jueves 16/01</td>
                        <td colspan="2">
                            <table class="table">
                                <tr>
                                    <td>Curso de Maquillaje 
                                        <p>Horario: 17:00 a 19:00</p></td>
                                    <td rowspan="2">Albergue Municipal</td>
                                </tr>
                                <tr>
                                    <td>Reunión Informativa con la Dirección de Cultura y la oficina de Protocolo.
                                        <p>Horario: 20:00 a 22:00</p></td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                    <tr>
                        <td>Viernes 17/01</td>
                        <td colspan="2">
                            <table class="table">
                                <tr>
                                    <td><p>Cata y Degustación de Vinos Caseros.</p>
                                        <p>Charla Promoción Económica.</p>
                                        <p>Charla sobre Obras y Servicios del departamento.</p> 
                                        <p>Horario: 08:00 a 13:00</p></td>
                                    <td>Albergue Municipal</td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                    <tr>
                        <td>Sabado 18/01</td>
                        <td colspan="2">
                            <table class="table">
                                <tr>
                                    <td>Presentación de Reinas en la Casa de la Cultura "Juanita Vera".
                                        <p>Horario: 21:00</p></td>
                                    <td>Casa de la Cultura de Villa Tulumaya</td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                    <tr>
                        <td>Domingo 19/01</td>
                        <td colspan="">
                            <table class="table">
                                <tr>
                                    <td>Presentación de Reinas en el distrito de Costa de Araujo (Concentración de salida y regreso desde la explanada municipal).
                                        <p>Horario: 20:00</p></td>
                                    <td>Plaza de Costa de Araujo (21:00)</td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                    <tr>
                        <td>Lunes 20/01</td>
                        <td colspan="2">
                            <table class="table">
                                <tr>
                                    <td>Presentación de Reinas en el distrito de Gustavo André(Concentración de salida y regreso desde la explanada municipal).
                                        <p>Horario: 20:00</p></td>
                                    <td>Playón deportivo de Gustavo André (21:00)</td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                    <tr>
                        <td>Martes 21/01</td>
                        <td colspan="2">
                            <table class="table">
                                <tr>
                                    <td>Presentación de Reinas en el Banco Credicoop(Concentración de salida y regreso desde la explanada municipal).
                                        <p>Horario: 20:00.</p>
                                        <p><strong>Ensayo en escenario después de agasajo en el banco</strong></p></td>
                                    <td>Playón deportivo de Gustavo André (21:00)</td>
                                </tr>
                            </table>

                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div><!-- FIN AGENDA VENDIMIAL -->

</div>
<?php if ($this->candidatas) : ?>
    <div id="Candidatas" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="candidatasLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="candidatasLabel">Candidatas Departamentales 2014</h3>
        </div>
        <div class="modal-body">

            <div id="CarouselCandidatas" class="carousel slide" data-interval="false"> 

                <div class="carousel-inner">
                    <?php foreach ($this->candidatas as $index => $candidata) : ?>
                        <?php if ($index == 0): ?>
                            <div class="item active">
                                <div class="media">
                                    <a class="pull-left" href="#">
                                        <?php if ($candidata->getImagenPrincipal() != null) : ?>
                                            <img class="media-object" src="<?php echo $this->baseUrl() . '/img/candidatas/' . $candidata->getImagenPrincipal() ?>">
                                        <?php else: ?>
                                            <img class="media-object" data-src="holder.js/64x64">
                                        <?php endif ?>

                                    </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><?php echo $candidata->getNombre() ?></h4>
                                        <br>
                                        <br>
                                        <p>Representa a: <?php echo $candidata->getLocalidad() ?> </p>
                                        <br>
                                        <p>Edad: <?php echo $candidata->getEdad() ?></p>       
                                        <br>
                                        <p>Ojos: <?php echo $candidata->getOjos() ?></p>
                                        <br>
                                        <p>Cabello: <?php echo $candidata->getCabello() ?></p>
                                        <br>
                                        <p>Estudios: <?php echo $candidata->getEstudios() ?> </p>
                                        <br>
                                        <p>Hobby: <?php echo $candidata->getHobby() ?></p>
                                        <br><br><br>
                                        <p>Votos: <span id='votos<?php echo $candidata->getId() ?>' class="badge badge-success"><?php echo $candidata->getVotos() ?></span>
                                            <?php if (!isset($_COOKIE['votoVendimia' . $candidata->getId()])): ?>
                                                <a class='votoVendimia btn btn-success' candidata="<?php echo $candidata->getId() ?>">+1</a> 
                                                <?php
                                            endif;
                                            ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        <?php else: ?>
                            <div class="item ">
                                <div class="media">
                                    <a class="pull-left" href="#">
                                        <?php if ($candidata->getImagenPrincipal() != null) : ?>
                                            <img class="media-object" src="<?php echo $this->baseUrl() . '/img/candidatas/' . $candidata->getImagenPrincipal() ?>">
                                        <?php else: ?>
                                            <img class="media-object" data-src="holder.js/64x64">
                                        <?php endif ?>

                                    </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><?php echo $candidata->getNombre() ?></h4>
                                        <br>
                                        <br>
                                        <p>Representa a: <?php echo $candidata->getLocalidad() ?> </p>
                                        <br>
                                        <p>Edad: <?php echo $candidata->getEdad() ?></p>       
                                        <br>
                                        <p>Ojos: <?php echo $candidata->getOjos() ?></p>
                                        <br>
                                        <p>Cabello: <?php echo $candidata->getCabello() ?></p>
                                        <br>
                                        <p>Estudios: <?php echo $candidata->getEstudios() ?> </p>
                                        <br>
                                        <p>Hobby: <?php echo $candidata->getHobby() ?></p>
                                        <br><br><br>
                                        <p>Votos: <span id='votos<?php echo $candidata->getId() ?>' class="badge badge-success"><?php echo $candidata->getVotos() ?></span>
                                            <?php if (!isset($_COOKIE['votoVendimia' . $candidata->getId()])): ?>
                                                <a class='votoVendimia btn btn-success' candidata="<?php echo $candidata->getId() ?>">+1</a> 
                                                <?php
                                            endif;
                                            ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>

                    <?php endforeach; ?>
                    <!--<a class="left carousel-control" href="#CarouselCandidatas" data-slide="next">&lsaquo;</a>-->

                </div>

            </div>

        </div>
        <div class="modal-footer">

            <div id="paginadorCandidatas" class='pagination'>
                <ul>
                    <?php foreach ($this->candidatas as $index => $candidata) : ?>
                        <?php if ($index == 0): ?>
                            <li data-target="#CarouselCandidatas" data-slide-to="<?php echo $index ?>" class="active"><a><?php echo $index + 1 ?></a></li>
                                <?php else: ?>
                            <li data-target="#CarouselCandidatas" data-slide-to="<?php echo $index ?>"><a><?php echo $index + 1 ?></a></li>
                        <?php endif; ?>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
<script>
    $('#paginadorCandidatas ul li a').on('click', function(e) {
        $('#paginadorCandidatas').find('.active').removeClass('active');
        $(this).parent().addClass('active');
    });
</script>
