<div class="well-large">
    <h1>Certificado Generado con éxito! </h1>
</div>
    <a href="<?php echo $this->baseUrl() . '/'.$this->pdf ?>" target="_blank" onClick="window.open(this.href, this.target, 'width=700,height=600');
return false;" role="button" class="btn btn-success" data-toggle="modal" ><h5>Abrir Licitacion <?php echo $this->licitacion->getNumero().'-'.$this->licitacion->getAnio()?>    </h5>
</a>