<!Doctype>
<html>
    <head>
        <title>Municipalidad de Lavalle</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php
        $a = '';
        echo $this->minifyHeadLink()
//                ->prependStylesheet($this->baseUrl() . $a . '/lights/luces.css')
                ->prependStylesheet($this->baseUrl() . $a . '/css/estilos.css')
                ->prependStylesheet($this->baseUrl() . $a . '/css/bootstrap-responsive.min.css')
                //->prependStylesheet($this->baseUrl() . $a.'/css/responsive.css')
                ->prependStylesheet($this->baseUrl() . $a . '/css/cubo/cubo.css')
                ->prependStylesheet($this->baseUrl() . $a . '/css/bootstrap.min.css')
                ->prependStylesheet($this->baseUrl() . $a . '/Gallery-master/css/blueimp-gallery.min.css');
        echo $this->headLink()
                ->headLink(array('rel' => 'icon',
                    'href' => $this->baseUrl() . '/img/Logo-16x16.png'), 'PREPEND');

        //        ->prependStylesheet($this->baseUrl() . '/css/bootstrap-responsive.css')

        echo $this->headMeta();
        ?>
        <script type="text/javascript" src="/min/?f=/js/jquery/js/jquery-1.10.2.min.js,/js/bootstrap.js"></script>
        <!--<script type="text/javascript" src="/min/?f=/public/js/jquery/js/jquery-1.10.2.min.js,/public/js/bootstrap.js"></script>-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-46658266-1']);
  _gaq.push(['_setDomainName', 'lavallemendoza.gov.ar']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

    </head>
    <body>
<!--        <div id="lights" class="visible-desktop">
             lights go here 
        </div>-->
        <div class="header">

            <div class="imagen-logo">
                <a href="<?php echo $this->url(array(), 'inicio', true) ?>" ><img src="<?php echo $this->baseUrl() . '/img/logo1.png' ?>"></a>
            </div>
            <!-- www.TuTiempo.net - Ancho:322px - Alto:79px -->
            <div class="pull-right visible-desktop" id="TT_vCjgrBdBdEh9dBsAKASEsEb1nWuALE1lrdEtEsCIK1D"><h2><a href="http://www.tutiempo.net">El tiempo en Lavalle</a></h2></div>
            <div class="navbar navbar-inverse mynav">
                <div class="navbar-inner">
                    <div class="container-fluid">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="brand" href="#"></a>
                        <div class="nav-collapse in collapse ">
                            <ul class="nav">
                                <li><a href="<?php echo $this->url(array(), 'inicio', true) ?>">inicio</a></li>
                                <?php echo $this->menuPrincipal(); ?>
                            </ul>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
        </div>

        <div id="container" class="container-fluid">

            <div class="row-fluid todo">

                <div class="span2 izquierda">
                    <div id="flotante1" class="affix flotanteabajo">
                        <?php echo $this->seccionCostado(0, 'azul', 'izquierda'); ?>

                        <?php echo $this->seccionCostado(1, 'naranja', 'izquierda'); ?>         
                        <ul class="nav nav-tabs nav-stacked naranja">
                            <li><a href="#farmacia" role="button" data-toggle="modal">Farmacia de turno</a></li>
                        </ul>
                    </div>
                </div>
                <div class="span8 contenidoCentral">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div class="span2 derecha">
                    <div id="flotante2" class="affix flotanteabajo">

                        <?php echo $this->seccionCostado(0, 'verde', 'derecha'); ?>
                        <ul class="nav nav-tabs nav-stacked azul">
                            <li><a href="<?php echo $this->url(array(),'hcd',true)?>">H C D</a></li>
                        </ul>
                        <br>
                        <div id="experiment">
                            <div id="cube">
                                <div class="face one">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />
                                </div>
                                <div class="face two">
                                    <br>
                                    <p style="text-align: center">HORARIO DE VERANO</p>
                                    <p style="text-align: center">DE 7:30 A 13:30 HS</p>
                                </div>
                                <div class="face three">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />    
                                </div>
                                <div class="face four">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/HACCREPOD.png"' ?>" />
                                </div>
                                <div class="face five">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />
                                </div>
                                <div class="face six">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div id="farmacia" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="farmaciaLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="farmaciaLabel">Farmacia de Turno</h3>
                </div>
                <div class="modal-body">
                    <center><h1>FARMACIA LAVALLE</h1></center>
                    <center><p></p></center>
                    <center><p></p></center>
                    <br>
                    <center><p>a partir de las 12 hs..!</p></center>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                </div>
            </div>
        </div>
        <?php
            echo $this->MinifyHeadScript()
                    ->appendFile($this->baseUrl() . $a . '/js/jchart/Chart.min.js')
                ->appendFile($this->baseUrl() . $a . '/js/jquery/cookie/jquery.cookie.js')
                ->appendFile($this->baseUrl() . $a . '/Gallery-master/js/blueimp-gallery.min.js')
                ->appendFile($this->baseUrl() . $a . '/js/frontend.js')
                ->appendFile($this->baseUrl() . $a . '/js/encuesta.js')
//                ->appendFile($this->baseUrl() . $a . '/js/yuiloader-min.js')
//                ->appendFile($this->baseUrl() . $a . '/js/yahoo-dom-event.min.js')
//                ->appendFile($this->baseUrl() . $a . '/lights/soundmanager2-nodebug-jsmin.js')
//                ->appendFile($this->baseUrl() . $a . '/js/animation-min.js')
//                ->appendFile($this->baseUrl() . $a . '/lights/christmaslights.js');
//        echo $this->InlineScript()
//                ->appendScript('
//                        var urlBase = "' . $this->baseUrl() . '/lights/";
//                        soundManager.url = "' . $this->baseUrl() . '/lights/";
//                        ')
                ->appendFile('http://www.tutiempo.net/widget/eltiempo_vCjgrBdBdEh9dBsAKASEsEb1nWuALE1lrdEtEsCIK1D');
        ?>
    </body>
</html>
