<!Doctype>
<html>
    <head>
        <title>Municipalidad de Lavalle</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta  http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link type="text/css" src="public/css/estilos.css"/>
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->baseUrl() . '/css/estilos.css')
                ->prependStylesheet($this->baseUrl() . '/css/bootstrap.css')
                ->prependStylesheet($this->baseUrl() . '/css/cubo/cubo.css')
                ->prependStylesheet($this->baseUrl() . '/lights/luces.css')
                ->headLink(array('rel' => 'icon',
            'href' => $this->baseUrl() . '/img/Logo-16x16.png'), 'PREPEND');
                
        //        ->prependStylesheet($this->baseUrl() . '/css/bootstrap-responsive.css')
      
        echo $this->headMeta();
        ?>
        <style type="text/css">
            body {
                padding-bottom: 40px;
            }
            .sidebar-nav {
                padding: 9px 0;
            }

            @media (max-width: 980px) {
                /* Enable use of floated navbar text */
                .navbar-text.pull-right {
                    float: none;
                    padding-left: 5px;
                    padding-right: 5px;
                }
            }
        </style>
        <!--<link href="/PaginaLavalle/public/css/bootstrap-responsive.css" media="screen" rel="stylesheet" type="text/css"/>-->
        <link href="<?php echo $this->baseUrl() . '/css/bootstrap-responsive.css' ?>" media="screen" rel="stylesheet" type="text/css"/>
        <?php
        echo $this->HeadScript()
                
                ->appendFile($this->baseUrl() . '/js/jquery/js/jquery-1.10.2.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap.js')
                ->appendFile($this->baseUrl() . '/js/jchart/Chart.min.js')
                ->appendFile($this->baseUrl() . '/js/jquery/cookie/jquery.cookie.js')
                ->appendFile($this->baseUrl() . '/js/frontend.js')
                ->appendFile($this->baseUrl() . '/js/encuesta.js');
                ?>
    </head>
    <body>
        <div id="lights">
                <!-- lights go here -->
            </div>
        <div class="header">

            <div class="imagen-logo">
                <a href="<?php echo $this->url(array(), 'inicio', true) ?>" ><img src="<?php echo $this->baseUrl() . '/img/logo1.png' ?>"></a>
            </div>
            <!-- www.TuTiempo.net - Ancho:322px - Alto:79px -->
            <div class="pull-right" id="TT_vCjgrBdBdEh9dBsAKASEsEb1nWuALE1lrdEtEsCIK1D"><h2><a href="http://www.tutiempo.net">El tiempo en Lavalle</a></h2></div>

        </div>

        <div id="container" class="container-fluid">
            
            <div class="row-fluid filaNavBar">
                <div class="span1"></div>
                <div class="span10">
                    <div class="navbar navbar-inverse navbar-static">
                        <div class="navbar-inner">
                            <div class="container-fluid">
                                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="brand" href="#"></a>
                                <div class="nav-collapse in collapse ">
                                    <ul class="nav">
                                        <li><a href="<?php echo $this->url(array(), 'inicio', true) ?>">inicio</a></li>
                                        <?php echo $this->menuPrincipal(); ?>
                                    </ul>
                                </div><!--/.nav-collapse -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span1"></div>
            </div>

            <div class="row-fluid todo">

                <div class="span2 izquierda">
                    <div id="flotante1" class="affix flotanteabajo">
                        <?php echo $this->seccionCostado(0, 'azul', 'izquierda'); ?>

                        <?php echo $this->seccionCostado(1, 'naranja', 'izquierda'); ?>         
                        <ul class="nav nav-tabs nav-stacked naranja">
                            <li><a href="#farmacia" role="button" data-toggle="modal">Farmacia de turno</a></li>
                        </ul>
                    </div>
                </div>
                <div class="span8 contenidoCentral">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div class="span2 derecha">
                    <div id="flotante2" class="affix flotanteabajo">

                        <?php echo $this->seccionCostado(0, 'verde', 'derecha'); ?>
                        <ul class="nav nav-tabs nav-stacked azul">
                            <li><a href="/secciones/ver/9">H C D</a></li>
                        </ul>
                        <br>
                        <div id="experiment">
                            <div id="cube">
                                <div class="face one">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />
                                </div>
                                <div class="face two">
                                    <p style="text-align: center">NUEVO HORARIO DE ATENCIÓN</p>
                                    <p style="text-align: center">DE 8 A 17 HS</p>
                                </div>
                                <div class="face three">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />    
                                </div>
                                <div class="face four">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/HACCREPOD.png"' ?>" />
                                </div>
                                <div class="face five">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />
                                </div>
                                <div class="face six">
                                    <img src="<?php echo $this->baseUrl() . '/css/cubo/images/logoVentanilla.png"' ?>" />
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div id="farmacia" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="farmaciaLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="farmaciaLabel">Farmacia de Turno</h3>
                </div>
                <div class="modal-body">
                    <center><h1>Farmacia Lavalle</h1></center>
                    <center><p>Ubicada en: Doctor Moreno 144</p></center>
                    <center><p>Teléfono: 4941022</p></center>
                    <br>
                    <center><p>a partir de las 12 hs..!</p></center>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                </div>
            </div>
        </div>
        <?php
        echo $this->InlineScript()
                ->appendFile($this->baseUrl() . '/js/yuiloader-min.js')
                ->appendFile($this->baseUrl() . '/js/yahoo-dom-event.min.js')
                ->appendFile($this->baseUrl() . '/lights/soundmanager2-nodebug-jsmin.js')
                ->appendFile($this->baseUrl() . '/js/animation-min.js')
                ->appendFile($this->baseUrl() . '/lights/christmaslights.js')
                ->appendScript('
                        var urlBase = "' . $this->baseUrl() . '/lights/";
                        soundManager.url = "' . $this->baseUrl() . '/lights/";
                        ')
//                ->appendFile('http://www.tutiempo.net/widget/eltiempo_vCjgrBdBdEh9dBsAKASEsEb1nWuALE1lrdEtEsCIK1D')
//                ->appendScript("
//                        (function(i, s, o, g, r, a, m) {
//        i['GoogleAnalyticsObject'] = r;
//        i[r] = i[r] || function() {
//            (i[r].q = i[r].q || []).push(arguments)
//        }, i[r].l = 1 * new Date();
//        a = s.createElement(o),
//                m = s.getElementsByTagName(o)[0];
//        a.async = 1;
//        a.src = g;
//        m.parentNode.insertBefore(a, m)
//    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
//
//    ga('create', 'UA-37852333-3', 'mendozalavalle.com.ar');
//    ga('send', 'pageview');
//
//                        ")
     ?>
    </body>
</html>
