<br /><br />

<div class="well">
    <h1>H C D</h1>
</div>

<a class="btn btn-primary" href="<?php echo $this->url(array(
    'module' => 'administracion', 
    'controller' => 'hcd',
    'action' => 'subir-documentos'
))?>">Nuevo Documento</a>
<table class="table">
    <tr>
        <th>Titulo</th>   
        <th>Documento</th>
        <th>Tipo</th>
    </tr>
    <?php if ($this->proyectos) :?>
    <?php foreach ($this->proyectos as $proyecto) : ?>
    <tr>
        <td><?php echo $proyecto->getTitulo()?></td>
        
        <td><a href="<?php echo $this->baseUrl() . '/proyectos/'.$proyecto->getDocumento() ?>" target="_blank" onClick="window.open(this.href, this.target, 'width=700,height=600');
return false;" role="button" data-toggle="modal" ><?php echo $proyecto->getDocumento()?></a></td>
        <td><?php echo $proyecto->getTipo()?></td>
    </tr>
    <?php endforeach; else: ?>
    <tr>No se encontraron Registros</tr>
    <?php endif;?>
</table>